### ISSUE TITLE
ModuleNotFoundError: No module named 'adutils'

### ISSUE THREAD

**Issue by antivirus68** [benleb/ad-ench#1]
_AppDaemon_ **4.1.0**
_Hassio_ **0.101.2**

I've just installed with HACS this nice app for Appdaemon.

When trying to add the ench app in appdaemon I got the following error:

`
2019-11-09 17:40:57.600347 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
`
`
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
`
`
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
`
`
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
`
`
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
`
`
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
`
`
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
`
`
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
`
`
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
`
`
  File "/config/appdaemon/apps/ench/ench.py", line 22, in <module>
    import adutils
`
`
ModuleNotFoundError: No module named 'adutils'
`

I see there is requirements.txt but it looks like the system doesn't bother about it.

Any idea?
What am I doing wrong?

Thanks
Marco

**Comment by benleb** [comment]
Did you try restarting the whole system? It seems Hassio/AppDaemon did not automatically pull the requirements from the requirements.txt

**Comment by antivirus68** [comment]
I've restarted, HA with no luck.
I'll try to restart Hassio.

Thanks Marco


Il Lun 11 Nov 2019, 11:14 Ben Lebherz <notifications@github.com> ha scritto:

**Comment by yevon** [comment]
same here, it doesn't download dependencies automatically?

**Comment by yevon** [comment]
Solved by setting this config to appdaemon plugin in home assistan hassio:

{
  "disable_auto_token": false,
  "system_packages": [],
  "python_packages": [
    "adutils"
  ]
}


But now the error is:

ModuleNotFoundError: No module named 'hassapi'

**Comment by yevon** [comment]
Changing 

import hassapi as hass

to

import appdaemon.plugins.hass.hassapi as hass

fixes the issue, working now!

**Comment by benleb** [comment]
thanks for finding a solution! 

but it seems that appdaemon or appdaemon with hacs/hassio doest handle this correctly :/

**Comment by CodeFinder2** [comment]
First of all, this issue seems to address two different problems:

1. dependencies (although defined in `requirements.txt` as usual for Python packages) are not correctly installed
2. error `ModuleNotFoundError: No module named 'hassapi'` during startup of AppDaemon while loading EnCh

The problem (1) seems to be here that only native Docker installs care about `requirements.txt` at all. So HassIO users (like me as well) are out of luck, see [here](https://community.home-assistant.io/t/heaty-will-die-schedy-be-born/71276/108).

Regarding (2): this seems okay since it will most probably only be supported in AppDaemon 4.x, see [here](https://github.com/home-assistant/appdaemon/issues/440) (`import hassapi as hass` is newer).

You should install dependencies using the HassIO addon configuration:
```json
{
  "disable_auto_token": false,
  "system_packages": [],
  "python_packages": [
    "adutils"
  ]
}
```
This is really ugly since every AppDaemon app should be able (also in HassIO) to define its dependencies on its own. Now, an additional step is necessary. If anyone knows a better solution (I didn't find one yet), please let me know. See also [this post](https://community.home-assistant.io/t/importing-librarys/101179). (Clearly, note that the `dependencies:` tag in `apps.yaml` only reflects dependencies between apps.) @benleb  Can you thing of another way than adding all deps manually to the addon config as shown above?

I've [created a PR](https://github.com/benleb/ad-ench/pull/4) to address the "import error" (2) issue in a generic way (i.e., should work for everyone).
