### ISSUE TITLE
Support for new appdaemon release

### ISSUE THREAD

**Issue by johntdyer** [benleb/ad-ench#10]
Hass.io just have 5.0.0 version of app daemon release, does this mean your now able to use the GA release vs the tip of tree version ?

**Comment by benleb** [comment]
The version 5.0.0 is the version of the Addon itself. It still provides you AppDaemon 3.x (https://github.com/hassio-addons/repository/tree/master/appdaemon3). Any newer AppDaemon (most recent is 4.x beta) also works :)

But since a few days and the support of @CodeFinder2, ad-ench works also on AppDaemon 3.0 :) So, give it a try 👍

**Comment by benleb** [comment]
To make things easier, I created a new AppDaemon 3.x compatible variant of EnCh. You (and @CodeFinder2) can use that one in the meantime :) https://github.com/benleb/ad-ench-ad3

**Comment by CodeFinder2** [comment]
@benleb Honestly, it's a bit weird that your latest official release just supports / requires a (BETA) version of AppDaemon that is not even released officially. I would have expected to release a dev/beta variant of **your app** supporting latest features of AppDaemon-beta but not the other way round. And for now, the only benefit seems to be performance which (IMHO) isn't that important in an app that's only doing some periodic polling.

This way and using your "alternative" ad-ench-ad3 repo, I would not be able to benefit from, e. g., the "stale entity check". It's also a bit strange to now uninstall ad-ench and reinstall ad-ench-ad3. Also asking to support AD v4 in the AD hassio addon makes no sense since they wouldn't do it (which makes sense it's still a beta). 🙈

Not sure yet what I will finally do about this; for now, I will stick to my current working setup that we used for debugging. 😉

But just my 2 cents! 😊

**Comment by benleb** [comment]
@CodeFinder2 my apps all support just the beta which you can get here as official releases https://github.com/home-assistant/appdaemon/releases
and i think its clearly stated in the readme. AD4 is around since month, its no bleeding-edge code in a feature branch.

the stale entities feature is much easier to implement in AD4 due to the new date & time helper functions added, read here if interested https://appdaemon.readthedocs.io/en/dev/HISTORY.html
and you are right regarding the performance and such, but i create these apps not with the primary goal to support a Hass.io setups or other (in my view weird) things like that, sorry. In a virtual-env or docker AD4 absolutely no problem to use and also as stable as needed.

for now, i really would suggest you to do nothing but just wait a **very little** and you will get AD4 stable and soon after, @frenck will probably also release the Hass.io addon with it  ;)

**Comment by benleb** [comment]
AppDaemon 4.0 releases :) https://community.home-assistant.io/t/announcement-appdaemon-v4-0-0/162846

**Comment by CodeFinder2** [comment]
Yeah, and that's fine in principle, don't get me wrong :see_no_evil: : you can surely support AD, also in a beta - whatever you want. I was just wondering to support a beta version of a library (exclusively), effectively excluding users of hassio. It made me think to stop using the app or fork it to provide a custom variant (which is fortunately, no longer necessary due to the release of AD4 and the upcoming new hassio addon including AD4).

Sure you are totally fine in excluding hassio as an ecosystem. I just wanted to let you know what consequences it might has, and to not just 'silently draw conclusions'. :see_no_evil:

Anyways, I think time is on our site: AD4 is released and the new addon is announced. :sunglasses:

**Comment by johntdyer** [comment]
where did you see the new add on being announced ?  i've been looking for just such an announcement and haven't seen it yet

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by CodeFinder2** [comment]
@johntdyer 
https://github.com/hassio-addons/addon-appdaemon3/issues/61

**Comment by benleb** [comment]
@johntdyer @frenck announced in discord that the addon including AD4 will be released today 🎉 

@CodeFinder2 next time I will stay compatible to the old version 😉😄👍

**Comment by CodeFinder2** [comment]
> @johntdyer @frenck announced in discord that the addon including AD4 will be released today 
> 
> @CodeFinder2 next time I will stay compatible to the old version

Great to hear that! :-)

**Comment by CodeFinder2** [comment]
Just to let you know @benleb : updated to AD 4 addon on hassio and now using v0.5.1 successfully! 🙂
