### ISSUE TITLE
No dependancy on adutils?

### ISSUE THREAD

**Issue by sj3fk3** [benleb/ad-ench#12]
Would it be possible to cut the cord with adultils so to speak? I don't really need or want the stuff adultils offers, but would like to try ench.. I've installed it once and edited out all the dependancy, but wouldn't it be better to have it more loosely coupled? Just I thought..

**Comment by benleb** [comment]
why do you want this? if it’s because there is an issue with installing the dependencies automatically, this is solved ;)
i already implemented the fix in my automoli app today and got positive feedback from testers. i will implement this in my other apps tomorrow.

if that’s not the case, why do you want it to be removed? 🤔

**Comment by benleb** [comment]
[v0.6.0](https://github.com/benleb/ad-ench/releases/tag/v0.6.0) fixes the dependency problems (hopefully on every possible setup...)
